# Generated by Django 4.0.6 on 2022-07-26 15:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Place1C',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idrref', models.TextField(db_column='_IDRRef', verbose_name='')),
                ('version', models.TextField(db_column='_Version', verbose_name='')),
                ('marked', models.TextField(db_column='_Marked', verbose_name='')),
                ('predefinedid', models.TextField(db_column='_PredefinedID', verbose_name='')),
                ('parentidrref', models.TextField(db_column='_ParentIDRRef', verbose_name='')),
                ('folder', models.TextField(db_column='_Folder', verbose_name='')),
                ('code', models.CharField(db_column='_Code', max_length=10, verbose_name='')),
                ('description', models.CharField(db_column='_Description', max_length=150, verbose_name='')),
                ('fld3015rref', models.TextField(blank=True, db_column='_Fld3015RRef', null=True, verbose_name='')),
                ('fld3058', models.TextField(blank=True, db_column='_Fld3058', null=True, verbose_name='')),
                ('fld3059', models.DecimalField(blank=True, db_column='_Fld3059', decimal_places=0, max_digits=3, null=True, verbose_name='')),
                ('fld3060', models.DecimalField(blank=True, db_column='_Fld3060', decimal_places=0, max_digits=5, null=True, verbose_name='')),
                ('fld3061', models.DecimalField(blank=True, db_column='_Fld3061', decimal_places=3, max_digits=10, null=True, verbose_name='')),
                ('fld3062', models.CharField(db_column='_Fld3062', max_length=5, verbose_name='')),
                ('fld3063rref', models.TextField(blank=True, db_column='_Fld3063RRef', null=True, verbose_name='')),
                ('fld4166', models.CharField(blank=True, db_column='_Fld4166', max_length=100, null=True, verbose_name='')),
                ('fld4527', models.CharField(blank=True, db_column='_Fld4527', max_length=15, null=True, verbose_name='')),
                ('fld4530', models.CharField(blank=True, db_column='_Fld4530', max_length=150, null=True, verbose_name='')),
                ('fld8992', models.DecimalField(blank=True, db_column='_Fld8992', decimal_places=5, max_digits=15, null=True, verbose_name='')),
                ('fld10569', models.CharField(blank=True, db_column='_Fld10569', max_length=120, null=True, verbose_name='')),
                ('fld10576', models.CharField(blank=True, db_column='_Fld10576', max_length=15, null=True, verbose_name='')),
                ('fld10591', models.TextField(blank=True, db_column='_Fld10591', null=True, verbose_name='')),
                ('fld190rref', models.TextField(db_column='_Fld190RRef', verbose_name='')),
                ('fld2522rref', models.TextField(db_column='_Fld2522RRef', verbose_name='')),
                ('fld2973rref', models.TextField(db_column='_Fld2973RRef', verbose_name='')),
            ],
        ),
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place_1c', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='places.place1c')),
            ],
        ),
    ]
