# Generated by Django 4.0.6 on 2022-07-26 15:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Person1C',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idrref', models.TextField(db_column='_IDRRef')),
                ('version', models.TextField(db_column='_Version')),
                ('marked', models.TextField(db_column='_Marked')),
                ('predefinedid', models.TextField(db_column='_PredefinedID')),
                ('parentidrref', models.TextField(db_column='_ParentIDRRef')),
                ('folder', models.TextField(db_column='_Folder')),
                ('code', models.CharField(db_column='_Code', max_length=9)),
                ('description', models.CharField(db_column='_Description', max_length=100)),
                ('fld433', models.CharField(blank=True, db_column='_Fld433', max_length=50, null=True)),
                ('fld434', models.CharField(blank=True, db_column='_Fld434', max_length=50, null=True)),
                ('fld435', models.CharField(blank=True, db_column='_Fld435', max_length=50, null=True)),
                ('fld436rref', models.TextField(blank=True, db_column='_Fld436RRef', null=True)),
                ('fld437', models.CharField(blank=True, db_column='_Fld437', max_length=12, null=True)),
                ('fld438', models.CharField(blank=True, db_column='_Fld438', max_length=100, null=True)),
                ('fld439', models.DateTimeField(blank=True, db_column='_Fld439', null=True)),
                ('fld440', models.CharField(blank=True, db_column='_Fld440', max_length=250, null=True)),
                ('fld441', models.CharField(blank=True, db_column='_Fld441', max_length=100, null=True)),
                ('fld442', models.CharField(blank=True, db_column='_Fld442', max_length=100, null=True)),
                ('fld443', models.CharField(blank=True, db_column='_Fld443', max_length=50, null=True)),
                ('fld444', models.CharField(blank=True, db_column='_Fld444', max_length=13, null=True)),
                ('fld445rref', models.TextField(blank=True, db_column='_Fld445RRef', null=True)),
                ('fld1219', models.TextField(blank=True, db_column='_Fld1219', null=True)),
                ('fld1220', models.CharField(blank=True, db_column='_Fld1220', max_length=14, null=True)),
                ('fld1221', models.CharField(blank=True, db_column='_Fld1221', max_length=14, null=True)),
                ('fld1222', models.DateTimeField(blank=True, db_column='_Fld1222', null=True)),
                ('fld1223', models.TextField(blank=True, db_column='_Fld1223', null=True)),
                ('fld2786rref', models.TextField(blank=True, db_column='_Fld2786RRef', null=True)),
                ('fld2787', models.TextField(blank=True, db_column='_Fld2787', null=True)),
                ('fld2793', models.TextField(blank=True, db_column='_Fld2793', null=True)),
                ('fld3107', models.CharField(blank=True, db_column='_Fld3107', max_length=150, null=True)),
                ('fld3108', models.CharField(blank=True, db_column='_Fld3108', max_length=40, null=True)),
                ('fld3694', models.CharField(blank=True, db_column='_Fld3694', max_length=100, null=True)),
                ('fld3699', models.CharField(blank=True, db_column='_Fld3699', max_length=100, null=True)),
                ('fld8581', models.TextField(blank=True, db_column='_Fld8581', null=True)),
                ('fld2522rref', models.TextField(db_column='_Fld2522RRef')),
                ('fld2973rref', models.TextField(db_column='_Fld2973RRef')),
                ('fld7296', models.DateTimeField(db_column='_Fld7296')),
                ('fld7297', models.DateTimeField(db_column='_Fld7297')),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avatar', models.ImageField(default='defaultuser.jpg', upload_to='profile_images')),
                ('full_name', models.CharField(max_length=150)),
                ('connected_1c_profile', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='profiles.person1c')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
