# Generated by Django 4.0.6 on 2022-07-26 15:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AssetItem1C',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idrref', models.TextField(db_column='_IDRRef', verbose_name='Ссылка')),
                ('version', models.TextField(db_column='_Version', verbose_name='ВерсияДанных')),
                ('marked', models.TextField(db_column='_Marked', verbose_name='ПометкаУдаления')),
                ('predefinedid', models.TextField(db_column='_PredefinedID', verbose_name='ИмяПредопределенныхДанных')),
                ('owneridrref', models.TextField(db_column='_OwnerIDRRef', verbose_name='Владелец')),
                ('parentidrref', models.TextField(db_column='_ParentIDRRef', verbose_name='Родитель')),
                ('folder', models.TextField(db_column='_Folder', verbose_name='ЭтоГруппа')),
                ('code', models.CharField(db_column='_Code', max_length=7, verbose_name='Код')),
                ('description', models.CharField(db_column='_Description', max_length=150, verbose_name='Наименование')),
                ('fld1138', models.CharField(blank=True, db_column='_Fld1138', max_length=300, null=True, verbose_name='НаименованиеПолное')),
                ('fld1139', models.TextField(blank=True, db_column='_Fld1139', null=True, verbose_name='Изготовитель')),
                ('fld1140', models.TextField(blank=True, db_column='_Fld1140', null=True, verbose_name='НомерПаспорта')),
                ('fld1141', models.CharField(blank=True, db_column='_Fld1141', max_length=70, null=True, verbose_name='ЗаводскойНомер')),
                ('fld1142', models.DateTimeField(blank=True, db_column='_Fld1142', null=True, verbose_name='ДатаВыпуска')),
                ('fld1143', models.TextField(blank=True, db_column='_Fld1143', null=True, verbose_name='Комментарий')),
                ('fld1144', models.TextField(blank=True, db_column='_Fld1144', null=True, verbose_name='Автотранспорт')),
                ('fld1145', models.TextField(blank=True, db_column='_Fld1145', null=True, verbose_name='Модель')),
                ('fld2797rref', models.TextField(blank=True, db_column='_Fld2797RRef', null=True, verbose_name='СчетУчета')),
                ('fld2799rref', models.TextField(blank=True, db_column='_Fld2799RRef', null=True, verbose_name='СчетАмортизации')),
                ('fld2800', models.DateTimeField(blank=True, db_column='_Fld2800', null=True, verbose_name='ДатаВвода')),
                ('fld2801', models.DecimalField(blank=True, db_column='_Fld2801', decimal_places=1, max_digits=5, null=True, verbose_name='СрокИспользования')),
                ('fld2802rref', models.TextField(blank=True, db_column='_Fld2802RRef', null=True, verbose_name='ВидАмортизации')),
                ('fld2803', models.DecimalField(blank=True, db_column='_Fld2803', decimal_places=2, max_digits=5, null=True, verbose_name='ПроцентАмортизации')),
                ('fld2804rref', models.TextField(blank=True, db_column='_Fld2804RRef', null=True, verbose_name='СтатьяЗатратАмортизации')),
                ('fld2805rref', models.TextField(blank=True, db_column='_Fld2805RRef', null=True, verbose_name='СчетИнвестиций')),
                ('fld3129rref', models.TextField(blank=True, db_column='_Fld3129RRef', null=True, verbose_name='МестоХранения')),
                ('fld3144rref', models.TextField(blank=True, db_column='_Fld3144RRef', null=True, verbose_name='НалоговаяГруппа')),
                ('fld3145', models.TextField(blank=True, db_column='_Fld3145', null=True, verbose_name='МНМА')),
                ('fld3170rref', models.TextField(blank=True, db_column='_Fld3170RRef', null=True, verbose_name='СчетЗатрат')),
                ('fld3175', models.DateTimeField(blank=True, db_column='_Fld3175', null=True, verbose_name='ДатаЛиквидации')),
                ('fld3239rref', models.TextField(blank=True, db_column='_Fld3239RRef', null=True, verbose_name='ВидАктива')),
                ('fld3263', models.DecimalField(blank=True, db_column='_Fld3263', decimal_places=2, max_digits=15, null=True, verbose_name='ЛиквидационнаяСтоимость')),
                ('fld3698rref', models.TextField(blank=True, db_column='_Fld3698RRef', null=True, verbose_name='КодУКТВЭД')),
                ('fld3898rref', models.TextField(blank=True, db_column='_Fld3898RRef', null=True, verbose_name='СтавкаНДС')),
                ('fld4512', models.CharField(blank=True, db_column='_Fld4512', max_length=15, null=True, verbose_name='СтарыйИнвНомер')),
                ('fld4513', models.DecimalField(blank=True, db_column='_Fld4513', decimal_places=2, max_digits=15, null=True, verbose_name='СуммаФиксАмортизации')),
                ('fld4516', models.CharField(blank=True, db_column='_Fld4516', max_length=15, null=True, verbose_name='Штрихкод')),
                ('fld4735rref', models.TextField(blank=True, db_column='_Fld4735RRef', null=True, verbose_name='ГруппаМСФО')),
                ('fld4990', models.DecimalField(blank=True, db_column='_Fld4990', decimal_places=2, max_digits=15, null=True, verbose_name='СтоимостьПриобретенияБезНДС')),
                ('fld4991', models.DecimalField(blank=True, db_column='_Fld4991', decimal_places=2, max_digits=15, null=True, verbose_name='ПриобретениеНДС')),
                ('fld6075rref', models.TextField(blank=True, db_column='_Fld6075RRef', null=True, verbose_name='ВидДеятельностиАмортизации')),
                ('fld6127', models.TextField(blank=True, db_column='_Fld6127', null=True, verbose_name='АмортизацияВСчетДохода')),
                ('fld6128rref', models.TextField(blank=True, db_column='_Fld6128RRef', null=True, verbose_name='АмДоходСчетУчета')),
                ('fld6129rref', models.TextField(blank=True, db_column='_Fld6129RRef', null=True, verbose_name='АмДоходСчетДохода')),
                ('fld6130rref', models.TextField(blank=True, db_column='_Fld6130RRef', null=True, verbose_name='АмДоходСтатьяДохода')),
                ('fld9601', models.DecimalField(blank=True, db_column='_Fld9601', decimal_places=0, max_digits=1, null=True, verbose_name='АмортизацияУУ')),
                ('fld10200', models.TextField(blank=True, db_column='_Fld10200', null=True, verbose_name='ТелепрограммаЗакупная')),
                ('fld10201', models.TextField(blank=True, db_column='_Fld10201', null=True, verbose_name='ТелепрограммаСобственная')),
                ('fld10202', models.TextField(blank=True, db_column='_Fld10202', null=True, verbose_name='Спонсорская')),
                ('fld10203', models.TextField(blank=True, db_column='_Fld10203', null=True, verbose_name='МузыкальнаяСправкаНаличие')),
                ('fld10204', models.TextField(blank=True, db_column='_Fld10204', null=True, verbose_name='ПрограммаНаРесурсе')),
                ('fld10205', models.CharField(blank=True, db_column='_Fld10205', max_length=1000, null=True, verbose_name='ОписаниеУкр')),
                ('fld10206', models.CharField(blank=True, db_column='_Fld10206', max_length=1000, null=True, verbose_name='ОписаниеРус')),
                ('fld10207', models.TextField(blank=True, db_column='_Fld10207', null=True, verbose_name='ПрокатноеСвидетельствоНаличие')),
                ('fld10208', models.CharField(blank=True, db_column='_Fld10208', max_length=300, null=True, verbose_name='СканСсылкаМузСправка')),
                ('fld10209', models.CharField(blank=True, db_column='_Fld10209', max_length=300, null=True, verbose_name='СканСсылкаПрокат')),
                ('fld10220rref', models.TextField(blank=True, db_column='_Fld10220RRef', null=True, verbose_name='ПроизводствоПрограмм')),
                ('fld10256', models.DecimalField(blank=True, db_column='_Fld10256', decimal_places=0, max_digits=5, null=True, verbose_name='Хронометраж')),
                ('fld10257', models.DateTimeField(blank=True, db_column='_Fld10257', null=True, verbose_name='НачалоПериодаПоказа')),
                ('fld10258', models.DateTimeField(blank=True, db_column='_Fld10258', null=True, verbose_name='ОкончаниеПериодаПоказа')),
                ('fld10259rref', models.TextField(blank=True, db_column='_Fld10259RRef', null=True, verbose_name='ЯзыкВедущего')),
                ('fld10260rref', models.TextField(blank=True, db_column='_Fld10260RRef', null=True, verbose_name='ЯзыкВКадре')),
                ('fld10261rref', models.TextField(blank=True, db_column='_Fld10261RRef', null=True, verbose_name='ЯзыкАдаптации')),
                ('fld10445', models.DecimalField(blank=True, db_column='_Fld10445', decimal_places=2, max_digits=15, null=True, verbose_name='СуммаФиксАмортизацииНУ')),
                ('fld10483', models.DateTimeField(blank=True, db_column='_Fld10483', null=True, verbose_name='НачалоПрав')),
                ('fld10484', models.DateTimeField(blank=True, db_column='_Fld10484', null=True, verbose_name='ОкончаниеПрав')),
                ('fld10485', models.CharField(blank=True, db_column='_Fld10485', max_length=10, null=True, verbose_name='ХронометражЗакуп')),
                ('fld10549', models.TextField(blank=True, db_column='_Fld10549', null=True, verbose_name='ПереносноеУстройство')),
                ('fld10577', models.DecimalField(blank=True, db_column='_Fld10577', decimal_places=1, max_digits=5, null=True, verbose_name='СрокИспользованияУУ')),
                ('fld10742', models.TextField(blank=True, db_column='_Fld10742', null=True, verbose_name='ТехникаИтОтдела')),
                ('fld3817', models.TextField(db_column='_Fld3817', verbose_name='НеХозДеятельность')),
            ],
        ),
        migrations.CreateModel(
            name='AssetItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_1c', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='assets.assetitem1c')),
            ],
        ),
    ]
