# Generated by Django 4.0.6 on 2022-07-26 15:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Location1C',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period', models.DateTimeField(db_column='_Period', verbose_name='Период')),
                ('recordertref', models.TextField(db_column='_RecorderTRef', verbose_name='Регистратор T')),
                ('recorderrref', models.TextField(db_column='_RecorderRRef', verbose_name='Регистратор R')),
                ('lineno', models.DecimalField(db_column='_LineNo', decimal_places=0, max_digits=9, verbose_name='НомерСтроки')),
                ('active', models.TextField(db_column='_Active', verbose_name='Активность')),
                ('fld3163rref', models.TextField(db_column='_Fld3163RRef', verbose_name='Организация')),
                ('fld3164rref', models.TextField(db_column='_Fld3164RRef', verbose_name='НА')),
                ('fld3165rref', models.TextField(db_column='_Fld3165RRef', verbose_name='Проект')),
                ('fld3166rref', models.TextField(db_column='_Fld3166RRef', verbose_name='Физлицо')),
                ('fld3176rref', models.TextField(db_column='_Fld3176RRef', verbose_name='МестоХранения')),
            ],
        ),
        migrations.CreateModel(
            name='LocationLinks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location_1c', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='locations.location1c')),
            ],
        ),
    ]
